### ISSUE TITLE
Complete the documentation of the ROBOTOLOGY_USES_PYTHON option

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#28]
The ROBOTOLOGY_USES_PYTHON is not officially tested and documented, but has been around for some time. This issue is about supporting it "officially" and document it.

Recap as of March 2020:  
* [x] Make sure that the correct Python is found (see https://github.com/robotology/robotology-superbuild/issues/364)
* [x] Add documentation of the ROBOTOLOGY_USES_PYTHON option in the README, following the structure of other ROBOTOLOGY_USES_* options 
* [x] Make sure that the option is tested on all the platforms for which it is document to work in README  
* [x] Once the ROBOTOLOGY_USES_PYTHON  is documented, we can remove the `mark_as_advanced`.

**Comment by traversaro** [comment]
Original code in the README removed in https://github.com/robotology/robotology-superbuild/pull/31 :

## Python
Support for this dependency is enabled by the `ROBOTOLOGY_USES_PYTHON` CMake option.

### Configuration
**TODO**

### Check the installation
**TODO**

**Comment by traversaro** [comment]
@DanielePucci : @anqingd had problems in understanding out to install python bindings of `iDynTree` due to this missing documentation. As Python is quite used in the rl world, it would be nice to fix this documementation.

**Comment by DanielePucci** [comment]
Yes, can @anqingd fix this since he went through it?

**Comment by traversaro** [comment]
fyi @paolo-viceconte @diegoferigo @Nicogene

**Comment by traversaro** [comment]
Related issues and PR: 
* https://github.com/robotology/robotology-superbuild/pull/359
* https://github.com/robotology/robotology-superbuild/issues/364

**Comment by traversaro** [comment]
I edited the top issue description to update on the status as of March 2020.

**Comment by traversaro** [comment]
>     * Add documentation of the ROBOTOLOGY_USES_PYTHON option in the README, following the structure of other ROBOTOLOGY_USES_* options

This was fixed by https://github.com/robotology/robotology-superbuild/pull/82 .

**Comment by traversaro** [comment]
> Make sure that the option is tested on all the platforms for which it is document to work in README

Python is now tested just on Ubuntu. We should enable it also on macOS, and eventually also on Windows (probably using the Python shipped with Visual Studio?) or explicitly document that it is not supported this options on that platforms.

**Comment by traversaro** [comment]
> 
> 
> > Make sure that the option is tested on all the platforms for which it is document to work in README
> 
> Python is now tested just on Ubuntu. We should enable it also on macOS, and eventually also on Windows (probably using the Python shipped with Visual Studio?) or explicitly document that it is not supported this options on that platforms.

For testing Python on macOS and Windows probably the easiest option is to use conda (see https://github.com/robotology/robotology-superbuild/issues/477 and https://github.com/robotology/robotology-superbuild/issues/477).

**Comment by traversaro** [comment]
I think documentation of the option is complete, see https://github.com/robotology/robotology-superbuild/blob/master/doc/cmake-options.md#python .
