### ISSUE TITLE
Add full support for powershell in conda docs

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#890]
* [ ] Modify powershell section in https://github.com/robotology/robotology-superbuild/pull/885/files to specify that also `mamba` does not work, and so in general suggest ot stick to Command prompt
* [ ] Fix mamba use in powershell ( https://github.com/mamba-org/mamba/issues/1088 )
* [ ] Fix powershell in Gazebo ( https://github.com/conda-forge/gazebo-feedstock/issues/42 )
* [ ] (Optional) Fix powershell in ROS ( https://github.com/RoboStack/ros-noetic/issues/21 )

**Comment by traversaro** [comment]
Hopefully better docs should be provided in https://github.com/robotology/robotology-superbuild/pull/891 .
